# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-22 15:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homework', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecture',
            name='is_available',
            field=models.BooleanField(default=False),
        ),
    ]
