# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-23 10:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homework', '0003_auto_20160622_1857'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answersheet',
            name='slug',
            field=models.SlugField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='homework',
            name='slug',
            field=models.SlugField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='lecture',
            name='slug',
            field=models.SlugField(blank=True, max_length=100, null=True),
        ),
    ]
