# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-13 20:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homework', '0005_homework_lecturer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answersheet',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='homework',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
    ]
