# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-06 09:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='answer',
            field=models.TextField(null=True),
        ),
    ]
