# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-13 20:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_message_answer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='answer',
            field=models.TextField(blank=True, null=True),
        ),
    ]
